### ISSUE TITLE
请问能否更换一个图标？

### ISSUE THREAD

**Issue by ctexlive** [Mapaler/FastCopy-M#1]
还不如原版的fc漂亮，现在默认的是一个茅草头发的娃娃图标，不得不说，丑爆了，而且没有标识度．

**Comment by Mapaler** [comment]
ReadMe.md 内容看不懂的话 

还有纯中文发布贴 http://bbs.kafan.cn/thread-1820907-1-1.html

都写得有如何更换图标，你可以自己更改为任意动画（帧数也是可变的）。

换图标工具内默认带的就是FastCopy原始图标。

东方厨一眼就能认出来是河童子，我只是懒得自己设计，从同人动画里截的。其实是想用幻想乡最速——文文的。但是更想用本命芙兰、爱丽丝、凹梦但是都没现成的16x16像素动画。
