### ISSUE TITLE
右键拖动问题

### ISSUE THREAD

**Issue by yjd** [Mapaler/FastCopy-M#11]
右键拖动复制和移动，如何设置不显示窗口。或者叫隐藏窗口模式。

**Comment by yjd** [comment]
搞定，看了关闭的帖子解决了。
不过窗口会闪一下就是。

**Comment by Mapaler** [comment]
勾上各种不经确认就直接运行的设置吧，我还是比较喜欢自己掌控。如果要完全不显示恐怕得用命令行模式，平时复制就完全不显示窗口应该需求不大。
