### ISSUE TITLE
几个建议

### ISSUE THREAD

**Issue by yfdyh000** [Mapaler/FastCopy-M#12]
1. 常规设置 - 其他，“使用英语UI”并重启后的选项布局、顺序有差异，最好同步。
2. 需要重启的选项（英语UI、测试创建），建议设置后（选项保存后，界面关闭前）询问是否重启程序。
3. 英文版下的帮助-最新版，仍是原版URL。中文版下的“最新版URL”有点怪，“最新版本”就好。

**Comment by Mapaler** [comment]
你好，感谢反馈
1. 因为不同语言的长度、字体有区别，所以并不适合使用相同布局。英文与日文除了为了支持功能改变而必须修改的字符外，都保持与原作一致。如果我去改了，那么下次原作更新版本的时候又是一个大工程。
2. 本程序并没有频繁更换需重启选项的需求，一般配置好后就不用再管了。而且这个程序可以同时打开多个，可以在执行任务的时候同时修改设置，如果强制重启会有许多问题。我觉得没什么必要专门添加个重启。
3. 英文和日文界面的最新版URL到底用谁的URL我也一直很纠结，毕竟原版就有这两个语言了，他们没必要专门来用我的，论坛也是保留的原作者的URL，所以最新版本也先保留的原版的URL（其实我根本没有听说过FastCopy-M有这两个语言的使用者）。  
   “最新版URL”是按照日文原版写的，因为日文界面上直接写的汉字的“最新版URL”。英文界面是原作者翻译的，他的英语好像也不是很好 :smirk:，所以我觉得还是按照日文原版写比较好。

**Comment by yfdyh000** [comment]
1. 如果不是布局摆不下，顺序一致会比较好。不明白是哪个语言版本改过了。日文原版经常改顺序吗。
1. 上手或对照翻译时比较麻烦，要设置、关闭、手动启动，再检查。应该有方法仅终止本身（pid？）并启动。有任务执行，不知道能否检查，或者对话框中提醒。启动方法，也许可以参考“提权”？
1. 感觉作为程序本身，用另一个版本的URL作“最新版本”有点奇怪。就中文翻译来说，“最新版URL”就很怪，没讲清目的（显示/获取/打开），URL也是较陌生的术语（虽然本软件的使用者可能认识）。
1. 就第二项，如果悬停时有工具提示显示原英文乃至细则就最好了。但那将是大工程，估计难以实现、难以与原作者同步。
1. 软件不少地方没有accesskey，但原版好像就是这样。
2. 界面翻译上，感觉用半角括号会比全角括号美观一些。

以上只是建议。感谢本地化。

**Comment by Mapaler** [comment]
1. 日、英文是原作者直接VS IDE编辑的，如果我也用IDE会导致代码出现变化，下次改起来就很麻烦，所以我一般是尽量直接编辑文本。日、英我是直接拷贝原作代码，中文的顺序应该是3.0第一版时定下的，之后的新增功能都放在后面，所以可能出现了顺序不一。因为代码里都是一行一行顺序时对应的，但是具体对象位置的代码我也没法直接看出谁在前谁在后，所以不知道哪些顺序不一样。
2. 对比很简单，你可以先开一个不要关，改成其他语言后再开一个。  
  ![图](http://ww2.sinaimg.cn/large/6c84b2d6gy1fh7rt4wcqbj20lz0hdt9c.jpg)  
  不知道有什么需要不断地改设置重启的必要。
3. 最新版本地址的问题可以在下次进行修改，现在没有专门为这个更新版本的必要。你说的"最新版URL"改成“最新版本”应该也没什么问题。但整体来说翻译的话，毕竟日语里面有很多汉字，毕竟 日汉字->一个英语不好的日本人->英文->一个英语不好的中国人->中文 往往会导致一些奇怪的翻译，偏离原意，所以我是优先使用对应汉字。比如“差分”这个词汇意思很好理解，但我研究了很久都没在中文圈找到合适的短词汇（用差异总感觉有点不对），只能用较长的话来解释，所以我就保留了日文汉字。所以整个程序我就是有限参照日文原文翻译，其次再用英文补足看不懂的。  
  至于术语的问题，也是很纠结的，看到ACL（这TM是啥？）、AltStream（这TM又是啥？）翻不翻译，最开始我是觉得不翻译为好，但是后来发现很多人问，于是我就去查这东西到底是什么鬼。结果因为是英文缩写很难查到，最后好不容易查到了，决定还是翻译成对应的中文名来方便别人查找它的意思（中文名比较容易查到）。但是像MB我总不可能写成百万字节吧，“I/O”要是写成“输入/输出”也太繁杂了，FAT，NTFS、MD5、SHA1这些的中文名都是什么？但是需要修改这些设置的人，肯定也看得懂这些超基础的英文术语的意思啦。看不懂的I/O里面那个“重叠数”我也翻译成中文了，我至今不知道那个到底是什么意思，所以也不知道翻译的对不对。
4. 悬停工具提示就算有也应该是当前语言的解释而不是英文原文，这个没有必要，去看英文原版帮助就行了。而且这个是工具类的，基本常用的就那么几个功能，用熟了根本不会去看是什么意思。
5. 我不知道你说的accesskey是什么。
6. 见3，日文原文基本都是全角括号。

你可以在协议框架下按照自己喜好修改程序，还可以Pull requests

**Comment by Mapaler** [comment]
修改FastCopy2.ini内的“lcid”的值，可以决定软件启动的语言，值为"-1"，即当前系统默认语言。改成“1041”启动就是日文

| 语言 | 值 |
| ---- | ---- |
| 日文 | 1041 |
| 英文 | 1033 |
| 简体中文 | 2052 |
| 繁体中文 | 1028 |

**Comment by yfdyh000** [comment]
1. 应该是代码顺序或者某些索引与英文UI不一样吧。不知道统一是否有行高问题。
1. 是个好办法。上手时想对比中文翻译与英文原文，所以有反复切换。有些翻译没错误，但因为没有工具提示作详细解释，想确认一下翻译和理解是否正确和有无遗漏。阅读帮助是个办法，但较长。
1. 像这种简单选项，理解本意后直接意译比较好。
1. 差分是有点怪怪的，虽然理解上没问题。"复制不同"？不覆盖、大小和日期、保留较新。术语的翻译目前挺好的。重叠数就是异步I/O并行数量吧，可考虑译作“异步 I/O 并行数量”。
1. 主要是有关术语，虽然目前术语翻译良好，但有时想对比原文，比如“访问控制表属性”翻译正确，但在中文下是有歧义的，是访问“控制表属性”还是“访问控制表”属性，虽然懂的人自然懂。如果有工具提示就能省很多力气。直接用英文版也OK，但有时感觉陌生。
1. 访问键，就是Alt+字母那个，常用于菜单、按钮，文件(&F)那个。
1. 本地化时不必要完全遵照原文吧，日文中路径“\”还是“￥”呢。用半角括号更容易分清主次。

**Comment by Mapaler** [comment]
已采纳合适的部分，更新了，你也没细说哪些要改的，下次可以尝试 Pull requests
