### ISSUE TITLE
能不能补一个其他下载点，亚马逊被墙的厉害，文件下不下来啊

### ISSUE THREAD

**Issue by qaqz111** [Mapaler/FastCopy-M#17]
百度盘城通盘微信云OneDrive什么的都可以啊

**Comment by Mapaler** [comment]
https://www.appcgn.com/fastcopy-v3.html
我一般会把Release发给这个站长，他会抽时间更新他的页面。
下载方式多到手软，我自己才懒得传那么多呢。

**Comment by qaqz111** [comment]
很好，收藏了
