### ISSUE TITLE
加入暂停/继续传输的功能

### ISSUE THREAD

**Issue by Sokwva** [Mapaler/FastCopy-M#20]
其实我想问问有没有可能加入暂停/继续传输的功能，然后弄一个速度图标之类的。

**Comment by Mapaler** [comment]
本来就有啊
![image 6](https://user-images.githubusercontent.com/6565860/32152162-550dcfe2-bd5d-11e7-8bc7-716a6e7ca0f4.png)

**Comment by Sokwva** [comment]
谢谢
