### ISSUE TITLE
有计划更新3.40么?

### ISSUE THREAD

**Issue by yyjdelete** [Mapaler/FastCopy-M#21]

**Comment by Mapaler** [comment]
有一堆毫无卵用的“检查更新”的代码，更新信息部分非明文是加密的，比较头疼，这一块最好是完全重写，但我并不了解CPP。

**Comment by Mapaler** [comment]
把主要功能代码都搞好了，但是我研究了下检测更新代码，用了很多IPMsg的自己写的函数，要搞清楚太费时间了，我准备不卵它了，反正也没啥用。
