### ISSUE TITLE
关于右键快捷键冲突的问题，

### ISSUE THREAD

**Issue by peqing** [Mapaler/FastCopy-M#22]
FastCopy-M 的右键快捷键是D，系统的删除快捷键也是D，我习惯是选中文件，点击右键，键盘按D，空格确认删除，现在按D冲突了，两个D，如图，请问这么修改啊？
![_20171215114237](https://user-images.githubusercontent.com/9016218/34025912-85abd352-e18d-11e7-8afc-a626d7f2937e.png)

**Comment by peqing** [comment]
解决了，通过Restorator修改了FastEx64.dll字符串删除（&D）保存就好了

**Comment by Mapaler** [comment]
我一般是直接按Delete
