### ISSUE TITLE
关于最新版的疑问 360报警有勒索病毒？？？！！

### ISSUE THREAD

**Issue by lp7943** [Mapaler/FastCopy-M#23]
有勒索病毒？？？？？？？？！！！用最新版64位时，为什么传输的时候360会弹出FastCopy为勒索病毒的消息？两次出现在传输中的一个图片文件，一次为一个MP3文件，我直接无视忽略过去了，现在想想好可怕啊，有人能解答一下么？
如果真中这个病毒我该咋办啊。传输结束后用360扫描却没有任何结果，勒索病毒是扫不出来的么？
FastCopy-M_3.4.0.45_win-64bit 这个文件。
谢谢啦

**Comment by Mapaler** [comment]
我不知道，你可以试试原版有没有这个问题。若不信任可以自行检查源码和编译。

**Comment by lp7943** [comment]
去别的地方下了个绿色的FastCopy3.40移动文件时也显示有这个病毒，（若不信任可以自行检查源码和编译。）这个实在是不会啊，您能帮忙查一下么？没问题的话告知一下就行，我宁愿相信是360误报啊。谢谢啦。

**Comment by Mapaler** [comment]
我本开始搞来自己用的当然没问题，我的程序从来不搞数字签名（不会），我也不知道360对这个的判定特征是什么，印象中听人说过没有数字签名的容易被360认为有危险。因为360从高中开始给我的印象就不好，所以我一直拒绝使用360的产品。目前我用的其他杀毒软件没有对这个进行误报，你可以多方验证一下，或者把程序提交给360工程师看看他们的说法。

**Comment by Mapaler** [comment]
不过你说复制时才出现，我猜可能是FastCopy的复制程序流程有和勒索病毒加密文件过程有部分相似的特征码，导致了360行为识别启动主动防御导致的吧。所以直接扫描程序文件的被动防御才没有报毒。3.40引入了zlib这个库，是一个开源压缩库，也许部分勒索病毒也用的这个。

**Comment by lp7943** [comment]
感谢你的回复 ，我也不信有毒 ，只是每次弹出来很渗人。谢谢

在 2017-12-21 14:47:28，"枫谷剑仙" <notifications@github.com> 写道：


不过你说复制时才出现，我猜可能是FastCopy的复制程序流程有和勒索病毒加密文件过程有部分相似的特征码，导致了360主动防御启动导致的吧。

**Comment by lp7943** [comment]
感谢你的回复  ，我也不信有毒 ，只是每次弹出来很渗人。谢谢




在 2017-12-21 14:47:28，"枫谷剑仙" <notifications@github.com> 写道：


不过你说复制时才出现，我猜可能是FastCopy的复制程序流程有和勒索病毒加密文件过程有部分相似的特征码，导致了360主动防御启动导致的吧。

**Comment by Mapaler** [comment]
免费杀软我更推荐德国的[小红伞](http://www.iavira.com/)
