### ISSUE TITLE
字体问题。

### ISSUE THREAD

**Issue by GithByi** [Mapaler/FastCopy-M#25]
[改变的字体，UI的字体不是全部改变的吗？怎么只能改变一部分的字体啊？

**Comment by Mapaler** [comment]
![image 15](https://user-images.githubusercontent.com/6565860/34864481-795abd92-f7af-11e7-9621-9d0c244199e6.png)
我这里全都是微软雅黑，不知道你是什么情况

**Comment by GithByi** [comment]
![qq 20180112172047](https://user-images.githubusercontent.com/34955808/34868063-85e2beee-f7bd-11e7-93b9-1f6467b67c79.jpg)

**Comment by GithByi** [comment]
这修改了字体变这样，太奇怪了，用上个版本就不会有这个问题。

**Comment by GithByi** [comment]
![qq 20180112172047](https://user-images.githubusercontent.com/34955808/34868136-c8fc1ec8-f7bd-11e7-8417-cea820f14b44.jpg)

**Comment by Mapaler** [comment]
这种情况应该是字体不存在，也就是你的字体名称可能改错了。你是怎么改的

**Comment by GithByi** [comment]
直接选项-扩展设置-改变主界面字体，这样修改了的

**Comment by Mapaler** [comment]
我刚才测试了，即便是官方原版，选项-扩展设置-改变主界面字体，也只看到改变左边的文本框的字体
![image 16](https://user-images.githubusercontent.com/6565860/34868829-07ebfdf4-f7c0-11e7-802f-ecf2022152fe.png)
![image 17](https://user-images.githubusercontent.com/6565860/34868830-083a5b2a-f7c0-11e7-9c69-dec42fa24fa8.png)
FC-M也是相同的结果
![image 18](https://user-images.githubusercontent.com/6565860/34868903-37410324-f7c0-11e7-845f-097c5488f9b9.png)
为什么你电脑上会这样其实我也很奇怪……我也没用Win7了没法测试。
你需要整体换字体最好是自己修改资源文件里的字体名称，重新编译资源，[FastCopy-M 资源文件重编译/自动替换工具](https://github.com/Mapaler/FastCopy-M-Resources-Rebuild-Replace-Tools/)。

**Comment by GithByi** [comment]
原来这样，好吧，非常感谢你抽空回复，谢谢了。祝你每天好运。

**Comment by Mapaler** [comment]
1. 先下载[FastCopy-M Resources Rebuild & Replace Tools.zip](https://github.com/Mapaler/FastCopy-M-Resources-Rebuild-Replace-Tools/archive/master.zip)的zip压缩包，然后解压
2. 运行`Update resources source file.vbs`更新资源
3. 记事本编辑`resource`文件夹内的`FastCopy.rc`文件
4. 搜索`中文(简体，中国)`部分，把这里面的所有字体名改成你要的。（可以批量搜索替换）
![image 19](https://user-images.githubusercontent.com/6565860/34869199-1b1691e0-f7c1-11e7-9be2-0a39f19851c0.png)
5. 保存文件，把`FastCopy.exe`拖到`rebuild.bat`上面

**Comment by GithByi** [comment]
感谢教程，我直接下个了个MicrosoftYaHei字体放在系统里面，就可以了。应该是WIN7没有这个字体造成的。谢谢你了。感谢你的软件和回复。再见，没有问题麻烦你了。

**Comment by Mapaler** [comment]
Win7是自带微软雅黑的，你可能是没有Microsoft Yahei UI这个Win8开始才有的雅黑衍生字体
