### ISSUE TITLE
提问 有没有可能加入统计图的功能

### ISSUE THREAD

**Issue by Sokwva** [Mapaler/FastCopy-M#28]
有没有可能加入类似于Windows 8.1/10 资源管理器在传输文件时的速度和状况的条状统计图功能。

**Comment by Mapaler** [comment]
有可能，但是我不会加的，这个功能多半需要使用GDI+绘图，增加软件资源消耗（不使用GDI+则多半卡爆）。既没有增加性能改进，也没有明显的提升使用便捷度，对于实际使用意义不大。
其实我一般复制都是直接最小化不管它的，复制的时候我可以干其他事情，但为了看是否正在复制，才让任务栏图标也随复制进行动画（原版没有动画）。

你可以尝试询问原作者，看他如何回复。

**Comment by Sokwva** [comment]
明白，谢谢回复
