### ISSUE TITLE
可否再界面上添加快捷键?[ (&X) 这样的]

### ISSUE THREAD

**Issue by thomasmolover** [Mapaler/FastCopy-M#29]
我用RH自己做了中文的, 能否官方添加进去?

这里劣作仅供参考

https://drive.google.com/open?id=1EzqeWIgubGlRsByNrvG7jeUyf0wHdwGB

**Comment by Mapaler** [comment]
我现在在手机上，不知道你想表达的意思。

如果你是希望自定义菜单快捷键，也不必用rh来慢慢改，你可以直接改源码。
如果不会VS编译，你可以试试下面这个工具
https://github.com/Mapaler/FastCopy-M-Resources-Rebuild-Replace-Tools   
先更新资源文件，然后手动修改资源文件里的字符后，把fastcopy.exe拖上去替换新的资源。
