### ISSUE TITLE
有拦截ctrl+v的功能么？

### ISSUE THREAD

**Issue by gMan1990** [Mapaler/FastCopy-M#3]
类似teracopy。（use teracopy as default copy handler）

**Comment by Mapaler** [comment]
没有，因为主程序是绿色软件，原作者不想给explorer注入。主程序不需要安装可直接单独执行，配置保存到ini而不是注册表，都是非常绿色的表现。只有右键外壳扩展dll才是挂载到了explorer上，但这个是非常常见的右键菜单挂载方式，而且3.2甚至还加入了用户权限就能添加扩展，进一步降低高权限的请求。

我2011年左右也用过很长一段时间的teracopy，发现了拦截Ctrl+V的一些弊病，比如不能撤销，复制到高权限目标受阻等。且直接用Ctrl+V的多半是少量小文件，需要调用第三方复制软件的“大型需求”右键拖放感觉更方便（我用的资源管理器曾是Clover、现在是Total Commander）。所以我后来放弃了使用teracopy。我目前并不知道拦截Ctrl+V注入方式，就算知道了也并不一定有能力开发，再加上我对这个没有需求所以我根本就不会去研究。

**Comment by Mapaler** [comment]
> 的提高豆腐干地方
