### ISSUE TITLE
fast copy 3.50 已出

### ISSUE THREAD

**Issue by litianyuhehe** [Mapaler/FastCopy-M#30]
如题

**Comment by Mapaler** [comment]
改了超多东西，代码难搞，现在没时间

**Comment by Mapaler** [comment]
我觉得这是4.0级别的更新😂
我不想搞了，我想玩游戏

**Comment by litianyuhehe** [comment]
这么可爱，可以肛吗？

**Comment by ghost** [comment]
就在你们聊肛的时候，作者措不及防地出了3.51，赶紧更新！

**Comment by peqing** [comment]
不能撂挑子

**Comment by Mapaler** [comment]
不行，最近实在是太忙了，FC新版本改了很多代码，完美改进非常花时间，可以说和2.x升级到3.x难度差不多，我手头还有其他优先项目，暂时没空搞。

**Comment by Mapaler** [comment]
新版引入的功能很多是我以前添加的，比如新版文件夹选择、首页图标动画等，所以不是非常有必要现在更新。
不过因为官方的代码和我的不一样，所以只能选择其中一个了。官方的新版文件夹选择是要求Win7以上，我的是默认调用新版，发生错误回退到老版，所以Vista应该也能用新版吧，就是没试过。

**Comment by Mapaler** [comment]
发了个预览版，可以试试
