### ISSUE TITLE
软件比较

### ISSUE THREAD

**Issue by sunnyday2006** [Mapaler/FastCopy-M#31]
老实说，网上各种TeraCopy、FastCopy和ExtremeCopy的速度测评我并不完全相信。

请问一下：你觉得以上三款，在速度快、资源占用少等方面哪个更优秀？

**Comment by Mapaler** [comment]
反正别人写的你都不相信，那你自己实际做评测不是最让你信服的吗。
所有的软件加速复制都需要用到高速内存空间当作缓存，这个可以手动更改大小的，不应算资源占用。软件本身的资源占用，FastCopy肯定是最少的，毕竟几百K的容量在那里明摆着。
现在的硬件条件下，只有复制大量小文件，比较速度才有意义了，连续大文件速度都能达到硬件本身的限制。
<hr>
所以选择复制软件只需要比较功能了。
做个比喻：
FastCopy就像是一个扳手，非常轻巧拿上就能用；——极度轻量，但是找到合适的条件就很快完成工作
TeraCopy是一个电钻，有一个大工具箱搬来搬去；——配置麻烦，每次工作手动操作少，但是启动慢
ExtremeCopy是花钱请工人帮你。——要钱
<hr>
所以收费的ExtremeCopy不考虑了。
TeraCopy优点就是支持劫持系统复制/粘贴指令，用Ctrl+C/V就能复制粘贴了（但是会丢失撤销这一系统功能），所以用TeraCopy的其实不是在一那一点复制时间，而是在意的操作简便程度。
FastCopy轻便就是它最大的优点，少量小文件的复制粘贴我直接用系统自带的就行了，比用任何第三方软件都快（用过几年TeraCopy，劫持系统复制反而对我造成了困扰）。需要进行大文件，特别是大量小文件或者同步时才用专业复制软件。FastCopy可以直接跳过预估文件大小的过程直接开始复制，复制大量小文件时甚至能节省十几分钟（就是不知道还剩多少没复制），遇到复制错误也不会中断，自动跳过错误继续复制其他的（会显示错误日志）。另外FastCopy支持命令行和工作保存，制作备份、同步任务也是非常方便的，我在工作中用的比较多。

**Comment by sunnyday2006** [comment]
我用过FastCopy和ExtremeCopy，实际感觉差距不是特别大。正如你说的，只有在复制大量小文件时，速度才会显现出一些差别。这里感谢你的解答分享。

另外说个事，我最近想试一下安装包，但安装期间出现bug。系统是win7 sp1（32），版本是FastCopy-M v3.4.1.46，报错显示如下：
![2018-07-21_fs02](https://user-images.githubusercontent.com/41056743/43020674-69a8f03e-8c93-11e8-98c7-38c9146f5cb0.png)
![2018-07-21_fs03](https://user-images.githubusercontent.com/41056743/43020677-6e17bbb4-8c93-11e8-9806-9bf5bf7bf620.png)

**Comment by Mapaler** [comment]
那就别用了，我也从来都不测试这个安装程序的，都是直接用绿色版。

**Comment by sunnyday2006** [comment]
你这是秒回？我刚又编辑了一次。。

**Comment by sunnyday2006** [comment]
早上好。

**Comment by Mapaler** [comment]
早上好是什么鬼。
GitHub会给我推送回复的邮件，我手机又设置了邮箱，所以很快会收到，我手机上又装了GitHub的应用，所以能马上回复。

**Comment by sunnyday2006** [comment]
现在凌晨3点了。失眠睡不着发现你的回复。

我也是邮件推送。

早点休息。溜了。

**Comment by Mapaler** [comment]
反正完全没必要用setup.exe，直接自己放到程序文件夹，设置外壳扩展就好了，卸载也是关闭外壳扩展，然后(重启)删掉文件就行了。

**Comment by sunnyday2006** [comment]
行，我设置一下。

**Comment by Mapaler** [comment]
我超困的，睡了，不回复你了
