### ISSUE TITLE
希望做几个符合理解的翻译修改

### ISSUE THREAD

**Issue by kli2013** [Mapaler/FastCopy-M#32]
第一个:ACL,现在翻译的是访问控制表属性,老实说第一次看简直一头雾水,后来搜索了下才理解,所以我希望的翻译是:"复制文件 ACL 权限"或者"复制文件 ACL 权限列表",这样虽然很冗余,但是小白也能第一时间理解功能

第二个:AltStream,现在翻译的是交换数据流,这个时候的"交换"会让人搞不清楚是动词还是名词,所以我希望的翻译是:复制交换数据流

以上是把这2个选项的功能说清楚明白的翻译

**Comment by kli2013** [comment]
然后还有一个是JobMng
我觉得简体中文系统里更好的翻译是:任务
比现在的"工作管理"节约两个字
希望大家讨论一下

**Comment by Mapaler** [comment]
当初做这个的时候缺少工具，这些都是找了很多地方才勉强找到的中文翻译。
现在可以用微软提供的页面查一查官方的翻译，我现在在外地不便。
https://www.microsoft.com/zh-cn/language/

**Comment by Mapaler** [comment]
不知道为什么语言门户查不了东西，一直400错误
