### ISSUE TITLE
帮助文档404了

### ISSUE THREAD

**Issue by zuisong** [Mapaler/FastCopy-M#33]
http://mapaler.github.io/FastCopy-M/help-chs.html   404 进不去了

**Comment by Mapaler** [comment]
![screenshot 2018-08-13 10 51 30](https://user-images.githubusercontent.com/6565860/44010759-e749786e-9ee6-11e8-93f2-cad7e2b5e542.png)
并没有404

**Comment by zuisong** [comment]
的确是我的电脑的问题，全局代理就能进了，谢谢作者，打扰了
