### ISSUE TITLE
能不能增加copy到手机的功能

### ISSUE THREAD

**Issue by wbhinspector** [Mapaler/FastCopy-M#34]
安卓手机，手机用usb线插入windows电脑，电脑的资源管理器和totalcommander都能打开手机存储，copy东西，但fastcopy就看不到手机，点网络，能看到手机图标，但点进去是空的，什么也没有。

**Comment by Mapaler** [comment]
FastCopy使用系统基本api工作，所以不支持MTP模式（更何况MTP模式就算支持了速度也和直接复制没区别）
TotalCommander进手机也可以看到路径是一种特殊的网络路径而不是一般的本地路径，TC那么大自然可以加入很多支持，就不要拿来和几百K的FC比了。

**Comment by wbhinspector** [comment]
好吧，那我还是用FTP来传文件吧。。谢谢
