### ISSUE TITLE
请问以前有工作完成（粘帖、删除等）自动关闭软件，现在怎么没有了啊？

### ISSUE THREAD

**Issue by peqing** [Mapaler/FastCopy-M#4]
请问以前有工作完成（粘帖、删除等）自动关闭软件，现在怎么没有了啊？

**Comment by Mapaler** [comment]
非我更改的代码部分保持与原作者一致。你说的是哪个版本？在哪里？作用是什么

**Comment by peqing** [comment]
忘记哪个版本了，貌似原版吧，最近才用你编译的，作用是：比如，删除完毕，会自动退出fastcopy

**Comment by Mapaler** [comment]
我也测试了原版，一样不会自动退出。虽然印象里好像是自动退出，但是最近的几个版本测试都没有自动退出。请找一下具体的版本吧，以及是直接打开主程序操作还是用外壳扩展。

**Comment by Mapaler** [comment]
之前版本出现的使用右键任务完成后不会自动关闭的问题，是因为作者在新版取消了四个选项的默认值。
![image 5](https://cloud.githubusercontent.com/assets/6565860/21038036/676c409c-be0d-11e6-8316-e75c036121c1.png)
需要手动在外壳扩展里勾选“没有错误自动关闭”。为了维持体验不变，我也默认不打开，和作者保持一致。
![image 6](https://cloud.githubusercontent.com/assets/6565860/21038158/630cb670-be0e-11e6-813d-b2468f7c68f0.png)

**Comment by peqing** [comment]
哎呀，好久没上了，非常感谢您的具体解答，谢谢您。
