### ISSUE TITLE
xp系统无法使用，提示是不是有效的win32程序，原版无问题？请解决

### ISSUE THREAD

**Issue by blankvip** [Mapaler/FastCopy-M#6]

**Comment by Mapaler** [comment]
那是你系统是32位，但是下成了64位的版本，自己下32位版本即可。

**Comment by blankvip** [comment]
我下载的就是 32位的，但是在XP系统就提示不是win32程序，您可以试下

**Comment by Mapaler** [comment]
检查发现是平台工具集选择了不兼容XP的新工具集。给你编译了个支持XP的，放到Release了。推荐升级系统到Win7以上。
