### ISSUE TITLE
您好，一个建议，关于文件右键快捷键

### ISSUE THREAD

**Issue by peqing** [Mapaler/FastCopy-M#9]
文件右键会有两个快捷键，一个是系统原有的快捷键（D），一个是FastCopy-M的快捷键同样是（D），两个在一起冲突了，我删除文件，习惯文件邮件，键盘按D，空格键，就结束了

**Comment by Mapaler** [comment]
原作者就是这样设置的快捷键，你有什么样的建议？

**Comment by peqing** [comment]
我自己用软件修改了，把.dll文件中的字符串后面的（D）删了，我觉得和系统的冲突了，另外也可能和我个人的习惯不一样

**Comment by Mapaler** [comment]
解决了就好
